<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:include filename="inertial_macros.xacro" />


    <xacro:property name="chassis_length" value="0.60" />
    <xacro:property name="chassis_width" value="0.40" />
    <xacro:property name="chassis_height" value="0.20" />
    <xacro:property name="chassis_mass" value="1.0" />
    <xacro:property name="wheel_radius" value="0.075" />
    <xacro:property name="wheel_thickness" value="0.05" />
    <xacro:property name="wheel_mass" value="0.05" />
    <xacro:property name="wheel_offset_x" value="0.5" />
    <xacro:property name="wheel_offset_y" value="0.225" />
    <xacro:property name="wheel_offset_z" value="0.01" />
    <xacro:property name="platform_length" value="0.3" />
    <xacro:property name="platform_width" value="0.3" />
    <xacro:property name="platform_height" value="0.08" />
    <xacro:property name="body_length" value="0.3" />
    <xacro:property name="body_width" value="0.4" />
    <xacro:property name="body_height" value="0.3" />


    <material name="white">
        <color rgba="1 1 1 1" />
    </material>

    <material name="orange">
        <color rgba="1 0.3 0.1 1" />
    </material>

    <material name="blue">
        <color rgba="0.2 0.2 1 1" />
    </material>

    <material name="black">
        <color rgba="0 0 0 1" />
    </material>

    <material name="red">
        <color rgba="1 0 0 1" />
    </material>

    <material name="green">
        <color rgba="0 1 0 1" />
    </material>

    <material name="yellow">
        <color rgba="1 1 0 1" />
    </material>

    <material name="purple">
        <color rgba="0.5 0 0.5 1" />
    </material>

    <material name="cyan">
        <color rgba="0 1 1 1" />
    </material>

    <material name="magenta">
        <color rgba="1 0 1 1" />
    </material>

    <material name="gray">
        <color rgba="0.5 0.5 0.5 1" />
    </material>

    <material name="dark_gray">
        <color rgba="0.25 0.25 0.25 1" />
    </material>

    <material name="light_gray">
        <color rgba="0.75 0.75 0.75 1" />
    </material>

    <material name="brown">
        <color rgba="0.6 0.3 0.1 1" />
    </material>

    <material name="light_blue">
        <color rgba="0.5 0.7 1 1" />
    </material>

    <material name="lime">
        <color rgba="0.7 1 0 1" />
    </material>

    <material name="pink">
        <color rgba="1 0.6 0.8 1" />
    </material>

    <material name="teal">
        <color rgba="0 0.5 0.5 1" />
    </material>

    <material name="navy">
        <color rgba="0 0 0.5 1" />
    </material>

    <!-- BASE LINK -->

    <link name="base_link">

    </link>

    <!-- BASE_FOOTPRINT LINK -->

    <joint name="base_footprint_joint" type="fixed">
        <parent link="base_link" />
        <child link="base_footprint" />
        <origin xyz="0 0 0" rpy="0 0 0" />
    </joint>

    <link name="base_footprint">
    </link>


    <!-- CHASSIS LINK -->

    <joint name="chassis_joint" type="fixed">
        <parent link="base_link" />
        <child link="chassis" />
        <origin xyz="0 0 ${-wheel_offset_z}" />
    </joint>

    <link name="chassis">
        <visual>
            <origin xyz="${chassis_length/2} 0 ${chassis_height/2}" />
            <geometry>
                <box size="${chassis_length} ${chassis_width} ${chassis_height}" />
            </geometry>
            <material name="orange" />
        </visual>
        <collision>
            <origin xyz="${chassis_length/2} 0 ${chassis_height/2}" />
            <geometry>
                <box size="${chassis_length} ${chassis_width} ${chassis_height}" />
            </geometry>
        </collision>
        <xacro:inertial_box mass="0.5" x="${chassis_length}" y="${chassis_width}"
            z="${chassis_height}">
            <origin xyz="${chassis_length/2} 0 ${chassis_height/2}" rpy="0 0 0" />
        </xacro:inertial_box>
    </link>

    <gazebo reference="chassis">
        <material>Gazebo/Orange</material>
    </gazebo>

    <!-- LEFT WHEEL LINK -->

    <joint name="front_left_wheel_joint" type="continuous">
        <parent link="base_link" />
        <child link="front_left_wheel" />
        <origin xyz="${wheel_offset_x}  ${wheel_offset_y} 0" rpy="-${pi/2} 0 0" />
        <axis xyz="0 0 1" />
    </joint>

    <link name="front_left_wheel">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}" />
            </geometry>
            <material name="blue" />
        </visual>
        <collision>
            <geometry>
                <sphere radius="${wheel_radius}" />
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_thickness}"
            radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0" />
        </xacro:inertial_cylinder>
    </link>

    <gazebo reference="front_left_wheel">
        <material>Gazebo/Blue</material>
    </gazebo>

    <joint name="rear_left_wheel_joint" type="continuous">
        <parent link="base_link" />
        <child link="rear_left_wheel" />
        <origin xyz="${wheel_offset_x-0.4} ${wheel_offset_y} 0" rpy="-${pi/2} 0 0" />
        <axis xyz="0 0 1" />
    </joint>

    <link name="rear_left_wheel">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}" />
            </geometry>
            <material name="blue" />
        </visual>
        <collision>
            <geometry>
                <sphere radius="${wheel_radius}" />
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_thickness}"
            radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0" />
        </xacro:inertial_cylinder>
    </link>

    <gazebo reference="rear_left_wheel">
        <material>Gazebo/Blue</material>
    </gazebo>


    <!-- RIGHT WHEEL LINK -->

    <joint name="front_right_wheel_joint" type="continuous">
        <parent link="base_link" />
        <child link="front_right_wheel" />
        <origin xyz="${wheel_offset_x} ${-wheel_offset_y} 0" rpy="${pi/2} 0 0" />
        <axis xyz="0 0 1" />
    </joint>

    <link name="front_right_wheel">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}" />
            </geometry>
            <material name="blue" />
        </visual>
        <collision>
            <geometry>
                <sphere radius="${wheel_radius}" />
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_thickness}"
            radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0" />
        </xacro:inertial_cylinder>
    </link>

    <gazebo reference="front_right_wheel">
        <material>Gazebo/Blue</material>
    </gazebo>


    <joint name="rear_right_wheel_joint" type="continuous">
        <parent link="base_link" />
        <child link="rear_right_wheel" />
        <origin xyz="${wheel_offset_x-0.4} ${-wheel_offset_y} 0" rpy="${pi/2} 0 0" />
        <axis xyz="0 0 1" />
    </joint>

    <link name="rear_right_wheel">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}" />
            </geometry>
            <material name="blue" />
        </visual>
        <collision>
            <geometry>
                <sphere radius="${wheel_radius}" />
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_thickness}"
            radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0" />
        </xacro:inertial_cylinder>
    </link>

    <gazebo reference="rear_right_wheel">
        <material>Gazebo/Blue</material>
    </gazebo>



    <gazebo>
        <plugin
        filename="gz-sim-diff-drive-system"
        name="gz::sim::systems::DiffDrive">
            <topic>cmd_vel</topic>
            <!-- <frame_id>odom</frame_id> -->
            <child_frame_id>base_footprint</child_frame_id>
            <odom_topic>odom/unfiltered</odom_topic>
            <!-- <tf_topic>/tf</tf_topic> -->
        <left_joint>rear_left_wheel_joint</left_joint>
        <right_joint>rear_right_wheel_joint</right_joint>
            <wheel_separation>0.45</wheel_separation>
            <wheel_radius>${wheel_radius}</wheel_radius>
        <max_linear_acceleration>1</max_linear_acceleration>
        <min_linear_acceleration>-1</min_linear_acceleration>
        <max_angular_acceleration>2</max_angular_acceleration>
        <min_angular_acceleration>-2</min_angular_acceleration>
        <max_linear_velocity>0.5</max_linear_velocity>
        <min_linear_velocity>-0.5</min_linear_velocity>
        <max_angular_velocity>1</max_angular_velocity>
        <min_angular_velocity>-1</min_angular_velocity>        </plugin>
      </gazebo>

</robot>